### ISSUE TITLE
[bug] Your connection is not secure

### ISSUE THREAD

**Issue by gaocegege** [TennyZhuang/blog#1]
> Your connection is not secure
> 
> The owner of blog.zhuangty.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

http://blog.zhuangty.com/ works for me while https does not.

Browser: Firefox 58.0.2 (64-bit)

**Comment by gaocegege** [comment]
Good luck for your application for PingCAP :tada:

**Comment by TennyZhuang** [comment]
Fixed
